### ISSUE TITLE
Permission to use d20.js in Hubot script

### ISSUE THREAD

**Issue by MFazio23** [michaelenger/d20.js#4]
I've created a Hubot wrapper for d20.js and I want to make sure you're good with me publishing it out to npm.  Code's here - https://github.com/MFazio23/hubot-d20

Let me know if I gave you proper credit for the brains of the plugin too.

(Sorry for the question-as-an-issue.  I wasn't sure the best route for contacting you)

**Comment by michaelenger** [comment]
Yes, of course. Go ahead and do whatever you want with it :+1:

**Comment by MFazio23** [comment]
Thank you!
