### ISSUE TITLE
NaN when doing straight math

### ISSUE THREAD

**Issue by Vlek** [michaelenger/d20.js#7]
I've run into an issue using the d20 package where, if I give it just math like "20 + 4", then it returns NaN. Seems very odd that it should fail to perform a basic mathematical calculation.

**Comment by michaelenger** [comment]
I disagree with the idea of using it to do regular math, as it's meant for rolling dice only. However, returning `NaN` is the worst way to deal with input it doesn't understand. I'll have to fix that.
