### ISSUE TITLE
More complex rolls like the ones in Roll20

### ISSUE THREAD

**Issue by DonaldTsang** [michaelenger/d20.js#9]
A copy of their JS script https://ghostbin.com/paste/2n67m  
Reference: https://wiki.roll20.net/Dice_Reference

**Comment by mpathy** [comment]
+1
Would be amazing.
Roll20 has all that one needs.
Where is the license to that? The file has none.

**Comment by DonaldTsang** [comment]
@mpathy just clean room reverse engineer it, since they refused to hand us the code, I got it from their website.

**Comment by michaelenger** [comment]
@DonaldTsang @mpathy I'm sorry to inform you that I am no longer maintaining this repository. If anybody would like to take over the NPM package I'd gladly oblige.

**Comment by DonaldTsang** [comment]
@mpathy there are other options as well
https://github.com/mog13/DXJS
https://github.com/GreenImp/rpg-dice-roller
